"""Audits a DUMP_SCHEMA reply.

The schema is generated by walking the firmware's live menu tree, so this is the check that the
walk actually produced what a config UI needs: valid JSON, a JSON key on every editable field,
sane bounds, and no field reachable only by a path the walker had to truncate.

    python tests/checks/check_schema.py schema.json
    python tools/send_serial.py COM8 DUMP_SCHEMA -o schema.json && python tests/checks/check_schema.py schema.json

Exits non-zero if anything is wrong, so it can gate a release.
"""

import json
import sys

# Kinds that represent a stored setting, and therefore need a key to read and write it by.
EDITABLE_KINDS = {"bool", "int", "float", "enum", "text"}
# Kinds that carry a numeric range.
RANGED_KINDS = {"int", "float", "enum"}


def walk(node, path, out):
    label = node.get("label", "?")
    here = path + [label]
    out.append((node, " > ".join(here)))
    for child in node.get("children", []):
        walk(child, here, out)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    raw = open(sys.argv[1], encoding="utf-8").read().strip()
    try:
        schema = json.loads(raw)
    except json.JSONDecodeError as e:
        print(f"FAIL: reply is not valid JSON: {e}")
        # The most common cause is a truncated read, so say how far it got.
        print(f"      {len(raw)} bytes, ends with: {raw[-60:]!r}")
        sys.exit(1)

    print(f"ok: valid JSON, {len(raw)} bytes")
    for key in ("fw", "boardId", "wiringConfigured", "deviceSchemaVersion",
                "profileSchemaVersion", "activeProfileIndex", "activeModeCount"):
        print(f"  {key}: {schema.get(key, '<missing>')}")

    nodes = []
    for root in schema.get("tree", []):
        walk(root, [], nodes)

    errors = []
    warnings = []
    derived_or_live = []
    id_valued = []
    index_valued = []
    keys = {}
    counts = {}

    for node, path in nodes:
        kind = node.get("kind", "?")
        counts[kind] = counts.get(kind, 0) + 1
        key = node.get("key")

        if node.get("truncated"):
            errors.append(f"{path}: children truncated - kMaxDepth is too low")

        if kind in EDITABLE_KINDS:
            storage = node.get("storage", "config")
            if not key:
                # Only a config-backed field needs a key. "derived" is an editing view over fields
                # other rows already expose (per-stage RPM writing revRPM/idleRPM); "live" is
                # runtime state that is never persisted (the active fire mode). Both are legitimately
                # keyless, but they have to say so - an unmarked keyless field is a forgotten key.
                if storage == "config":
                    errors.append(
                        f"{path}: {kind} field has no key and is not marked derived/live")
                else:
                    derived_or_live.append(f"{path} ({storage})")
            elif storage != "config":
                errors.append(f"{path}: marked {storage} but still carries key {key!r}")
            else:
                # The same item is legitimately reachable by more than one path (shortcuts, and
                # submenus mounted in two places), so a repeat is only a problem if the label differs.
                if key in keys and keys[key] != node.get("label"):
                    errors.append(f"{path}: key {key!r} already used by {keys[key]!r}")
                keys[key] = node.get("label")
                if not (key.startswith("device:") or key.startswith("profile:")):
                    errors.append(f"{path}: key {key!r} is not scoped to a store")

        if kind in RANGED_KINDS:
            lo, hi, step = node.get("lo"), node.get("hi"), node.get("step")
            if lo is None or hi is None or step is None:
                errors.append(f"{path}: {kind} field is missing lo/hi/step")
            else:
                if lo > hi:
                    errors.append(f"{path}: lo {lo} > hi {hi}")
                if step <= 0:
                    errors.append(f"{path}: step is {step}")
                elif hi > lo and (hi - lo) < step:
                    warnings.append(f"{path}: range {lo}..{hi} is narrower than one step of {step}")

        if kind == "enum" and not node.get("options"):
            errors.append(f"{path}: enum has no options")

        # An enum backed by a C++ enum stores a name, and optionValues carries one per option (see
        # the firmware's enumIds.h). An enum without them stores a number because the number is the
        # meaning - a fire mode or profile index - so absence is legal and counted, not flagged.
        ids = node.get("optionValues")
        if ids is not None:
            id_valued.append(path)
            options = node.get("options") or []
            if len(ids) != len(options):
                errors.append(
                    f"{path}: {len(ids)} optionValues for {len(options)} options")
            # A duplicate id means two options share a stored value, so one of them can never be
            # read back - the failure mode a parallel id table is prone to.
            seen = {}
            for i, value in enumerate(ids):
                if value in seen:
                    errors.append(
                        f"{path}: optionValues[{i}] {value!r} duplicates [{seen[value]}]")
                seen[value] = i
                # Index 0 may be empty on purpose - it is how "nothing selected" is stored.
                if value == "" and i != 0:
                    errors.append(f"{path}: optionValues[{i}] is empty")
        elif kind == "enum":
            index_valued.append(path)

        if kind == "text" and not node.get("charset"):
            errors.append(f"{path}: text field has no charset")

    caps = schema.get("fireModeCaps")
    if caps is None:
        warnings.append("fireModeCaps is null - expected only when the mode list is full")
    else:
        for entry in caps:
            for field in entry.get("fields", []):
                if not field.get("key"):
                    errors.append(f"fireModeCaps[{entry.get('name')}]: field with no key")
                lo, hi = field.get("lo"), field.get("hi")
                if lo is not None and hi is not None and lo > hi:
                    errors.append(
                        f"fireModeCaps[{entry.get('name')}] {field['key']}: lo {lo} > hi {hi}")
        print(f"  fireModeCaps: {len(caps)} modes "
              f"({', '.join(e.get('name', '?') for e in caps)})")

    print(f"  {len(nodes)} nodes: " + ", ".join(f"{v} {k}" for k, v in sorted(counts.items())))
    print(f"  {len(keys)} distinct keys")
    print(f"  {len(id_valued)} enums store an id, {len(index_valued)} store an index")
    if index_valued:
        # Listed because an enum losing its ids looks exactly like one that never had them. These
        # should only ever be fire-mode and profile indices.
        for i in index_valued:
            print(f"      index-valued: {i}")
    if derived_or_live:
        print(f"  {len(derived_or_live)} intentionally keyless rows:")
        for d in derived_or_live:
            print(f"      {d}")

    for w in warnings:
        print(f"WARN: {w}")
    for e in errors:
        print(f"FAIL: {e}")

    if errors:
        print(f"\n{len(errors)} problem(s)")
        sys.exit(1)
    print("\nall checks passed")


if __name__ == "__main__":
    main()
